module Evergreen.Migrate.V13 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V13.Types
import Evergreen.V8.Types
import Lamdera.Migrations exposing (..)
import Maybe


frontendModel : Evergreen.V8.Types.FrontendModel -> ModelMigration Evergreen.V13.Types.FrontendModel Evergreen.V13.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V8.Types.BackendModel -> ModelMigration Evergreen.V13.Types.BackendModel Evergreen.V13.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V8.Types.FrontendMsg -> MsgMigration Evergreen.V13.Types.FrontendMsg Evergreen.V13.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V8.Types.ToBackend -> MsgMigration Evergreen.V13.Types.ToBackend Evergreen.V13.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V8.Types.BackendMsg -> MsgMigration Evergreen.V13.Types.BackendMsg Evergreen.V13.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V8.Types.ToFrontend -> MsgMigration Evergreen.V13.Types.ToFrontend Evergreen.V13.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_FrontendModel : Evergreen.V8.Types.FrontendModel -> Evergreen.V13.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , currentUser = old.currentUser
    , page = old.page |> migrate_Types_Page
    , currentRound = old.currentRound |> Maybe.map migrate_Types_FrontendRound
    , pastRounds = old.pastRounds
    , userGuess = old.userGuess
    , pendingLocation = old.pendingLocation
    , mapCenter = old.mapCenter |> migrate_Types_Location
    , mapZoom = old.mapZoom
    , avatarList = []
    , error = old.error
    , authData = old.authData
    }


migrate_Types_CensoredRound : Evergreen.V8.Types.CensoredRound -> Evergreen.V13.Types.CensoredRound
migrate_Types_CensoredRound old =
    old |> migrate_Types_Round identity identity


migrate_Types_FrontendRound : Evergreen.V8.Types.FrontendRound -> Evergreen.V13.Types.FrontendRound
migrate_Types_FrontendRound old =
    case old of
        Evergreen.V8.Types.Uncensored p0 ->
            Evergreen.V13.Types.Uncensored (p0 |> migrate_Types_UncensoredRound)

        Evergreen.V8.Types.Censored p0 ->
            Evergreen.V13.Types.Censored (p0 |> migrate_Types_CensoredRound)


migrate_Types_Guess : Evergreen.V8.Types.Guess -> Evergreen.V13.Types.Guess
migrate_Types_Guess old =
    { userId = old.userId
    , userName = old.userName
    , location = old.location |> migrate_Types_Location
    , timestamp = old.timestamp
    , distanceKm = old.distanceKm
    }


migrate_Types_Location : Evergreen.V8.Types.Location -> Evergreen.V13.Types.Location
migrate_Types_Location old =
    old


migrate_Types_Page : Evergreen.V8.Types.Page -> Evergreen.V13.Types.Page
migrate_Types_Page old =
    case old of
        Evergreen.V8.Types.LoginPage ->
            Evergreen.V13.Types.LoginPage

        Evergreen.V8.Types.GamePage ->
            Evergreen.V13.Types.GamePage

        Evergreen.V8.Types.ResultsPage p0 ->
            Evergreen.V13.Types.ResultsPage p0

        Evergreen.V8.Types.HistoryPage ->
            Evergreen.V13.Types.HistoryPage


migrate_Types_Round : (actualLocationType_old -> actualLocationType_new) -> (guessType_old -> guessType_new) -> Evergreen.V8.Types.Round actualLocationType_old guessType_old -> Evergreen.V13.Types.Round actualLocationType_new guessType_new
migrate_Types_Round migrate_actualLocationType migrate_guessType old =
    { id = old.id
    , actualLocation = old.actualLocation |> migrate_actualLocationType
    , startTime = old.startTime
    , endTime = old.endTime
    , guesses = old.guesses |> Dict.map (always migrate_guessType)
    , isOpen = old.isOpen
    }


migrate_Types_ToFrontend : Evergreen.V8.Types.ToFrontend -> Evergreen.V13.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V8.Types.AuthenticationResult p0 ->
            Evergreen.V13.Types.AuthenticationResult p0

        Evergreen.V8.Types.GameStateUpdate p0 ->
            Evergreen.V13.Types.GameStateUpdate
                { currentUser = p0.currentUser
                , currentRound = p0.currentRound |> Maybe.map migrate_Types_FrontendRound
                , usersGuess = p0.usersGuess
                , pastRounds = p0.pastRounds
                , avatarList = []
                }

        Evergreen.V8.Types.RoundCreated p0 ->
            Evergreen.V13.Types.RoundCreated (p0 |> migrate_Types_CensoredRound)

        Evergreen.V8.Types.GuessSubmitted p0 ->
            Evergreen.V13.Types.GuessSubmitted (p0 |> migrate_Types_Guess)

        Evergreen.V8.Types.RoundClosed p0 ->
            Evergreen.V13.Types.RoundClosed (p0 |> migrate_Types_UncensoredRound)

        Evergreen.V8.Types.ErrorMessage p0 ->
            Evergreen.V13.Types.ErrorMessage p0


migrate_Types_UncensoredRound : Evergreen.V8.Types.UncensoredRound -> Evergreen.V13.Types.UncensoredRound
migrate_Types_UncensoredRound old =
    old |> migrate_Types_Round migrate_Types_Location migrate_Types_Guess
