module Evergreen.Migrate.V25 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V23.Types
import Evergreen.V25.Types
import Lamdera.Migrations exposing (..)
import List
import Maybe


frontendModel : Evergreen.V23.Types.FrontendModel -> ModelMigration Evergreen.V25.Types.FrontendModel Evergreen.V25.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V23.Types.BackendModel -> ModelMigration Evergreen.V25.Types.BackendModel Evergreen.V25.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V23.Types.FrontendMsg -> MsgMigration Evergreen.V25.Types.FrontendMsg Evergreen.V25.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V23.Types.ToBackend -> MsgMigration Evergreen.V25.Types.ToBackend Evergreen.V25.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V23.Types.BackendMsg -> MsgMigration Evergreen.V25.Types.BackendMsg Evergreen.V25.Types.BackendMsg
backendMsg old =
    MsgMigrated ( migrate_Types_BackendMsg old, Cmd.none )


toFrontend : Evergreen.V23.Types.ToFrontend -> MsgMigration Evergreen.V25.Types.ToFrontend Evergreen.V25.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V23.Types.BackendModel -> Evergreen.V25.Types.BackendModel
migrate_Types_BackendModel old =
    { users = old.users
    , rounds = old.rounds |> List.map migrate_Types_UncensoredRound
    , userSessions = old.userSessions
    , failedAuthentications = old.failedAuthentications
    , now = old.now
    }


migrate_Types_FrontendModel : Evergreen.V23.Types.FrontendModel -> Evergreen.V25.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , currentUser = old.currentUser
    , page = old.page |> migrate_Types_Page
    , currentRound = old.currentRound |> Maybe.map migrate_Types_FrontendRound
    , pastRounds = old.pastRounds |> List.map migrate_Types_UncensoredRound
    , userGuess = old.userGuess
    , pendingLocation = old.pendingLocation
    , prompt = ""
    , mapCenter = old.mapCenter |> migrate_Types_Location
    , mapZoom = old.mapZoom
    , avatarList = old.avatarList
    , error = old.error
    , authData = old.authData
    }


migrate_Types_BackendMsg : Evergreen.V23.Types.BackendMsg -> Evergreen.V25.Types.BackendMsg
migrate_Types_BackendMsg old =
    case old of
        Evergreen.V23.Types.NoOpBackendMsg ->
            Evergreen.V25.Types.NoOpBackendMsg

        Evergreen.V23.Types.Tick p0 ->
            Evergreen.V25.Types.Tick p0


migrate_Types_FrontendMsg : Evergreen.V23.Types.FrontendMsg -> Evergreen.V25.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V23.Types.UrlClicked p0 ->
            Evergreen.V25.Types.UrlClicked p0

        Evergreen.V23.Types.UrlChanged p0 ->
            Evergreen.V25.Types.UrlChanged p0

        Evergreen.V23.Types.InitiateTelegramAuth ->
            Evergreen.V25.Types.InitiateTelegramAuth

        Evergreen.V23.Types.TelegramAuthResult p0 ->
            Evergreen.V25.Types.TelegramAuthResult p0

        Evergreen.V23.Types.Logout ->
            Evergreen.V25.Types.Logout

        Evergreen.V23.Types.LoginAsRay ->
            Evergreen.V25.Types.LoginAsRay

        Evergreen.V23.Types.LoginAsRegularUser ->
            Evergreen.V25.Types.LoginAsRegularUser

        Evergreen.V23.Types.MapClicked p0 ->
            Evergreen.V25.Types.MapClicked (p0 |> migrate_Types_Location)

        Evergreen.V23.Types.StartNewRound ->
            Evergreen.V25.Types.StartNewRound

        Evergreen.V23.Types.ConfirmStartRound ->
            Evergreen.V25.Types.ConfirmStartRound

        Evergreen.V23.Types.CancelPendingLocation ->
            Evergreen.V25.Types.CancelPendingLocation

        Evergreen.V23.Types.SubmitGuess ->
            Evergreen.V25.Types.SubmitGuess

        Evergreen.V23.Types.CloseRound ->
            Evergreen.V25.Types.CloseRound

        Evergreen.V23.Types.ViewRound p0 ->
            Evergreen.V25.Types.ViewRound p0

        Evergreen.V23.Types.GoToHistory ->
            Evergreen.V25.Types.GoToHistory

        Evergreen.V23.Types.GoToGame ->
            Evergreen.V25.Types.GoToGame

        Evergreen.V23.Types.ClearError ->
            Evergreen.V25.Types.ClearError

        Evergreen.V23.Types.NoOpFrontendMsg ->
            Evergreen.V25.Types.NoOpFrontendMsg


migrate_Types_FrontendRound : Evergreen.V23.Types.FrontendRound -> Evergreen.V25.Types.FrontendRound
migrate_Types_FrontendRound old =
    case old of
        Evergreen.V23.Types.Uncensored p0 ->
            Evergreen.V25.Types.Uncensored (p0 |> migrate_Types_UncensoredRound)

        Evergreen.V23.Types.Censored p0 ->
            Evergreen.V25.Types.Censored (p0 |> migrate_Types_CensoredRound)


migrate_Types_Guess : Evergreen.V23.Types.Guess -> Evergreen.V25.Types.Guess
migrate_Types_Guess old =
    { userId = old.userId
    , userName = old.userName
    , location = old.location |> migrate_Types_Location
    , timestamp = old.timestamp
    , distanceKm = old.distanceKm
    }


migrate_Types_Location : Evergreen.V23.Types.Location -> Evergreen.V25.Types.Location
migrate_Types_Location old =
    old


migrate_Types_Page : Evergreen.V23.Types.Page -> Evergreen.V25.Types.Page
migrate_Types_Page old =
    case old of
        Evergreen.V23.Types.LoginPage ->
            Evergreen.V25.Types.LoginPage

        Evergreen.V23.Types.GamePage ->
            Evergreen.V25.Types.GamePage

        Evergreen.V23.Types.ResultsPage p0 ->
            Evergreen.V25.Types.ResultsPage p0

        Evergreen.V23.Types.HistoryPage ->
            Evergreen.V25.Types.HistoryPage


migrate_Types_ToBackend : Evergreen.V23.Types.ToBackend -> Evergreen.V25.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V23.Types.AuthenticateWithTelegram p0 ->
            Evergreen.V25.Types.AuthenticateWithTelegram p0

        Evergreen.V23.Types.LogoutUser ->
            Evergreen.V25.Types.LogoutUser

        Evergreen.V23.Types.AuthenticateAsRay ->
            Evergreen.V25.Types.AuthenticateAsRay

        Evergreen.V23.Types.AuthenticateAsRegularUser ->
            Evergreen.V25.Types.AuthenticateAsRegularUser

        Evergreen.V23.Types.CreateNewRound p0 ->
            Evergreen.V25.Types.RequestRoundHistory

        Evergreen.V23.Types.SubmitUserGuess p0 ->
            Evergreen.V25.Types.SubmitUserGuess (p0 |> migrate_Types_Location)

        Evergreen.V23.Types.EndCurrentRound ->
            Evergreen.V25.Types.EndCurrentRound

        Evergreen.V23.Types.RequestCurrentGameState ->
            Evergreen.V25.Types.RequestCurrentGameState

        Evergreen.V23.Types.RequestRoundHistory ->
            Evergreen.V25.Types.RequestRoundHistory


migrate_Types_ToFrontend : Evergreen.V23.Types.ToFrontend -> Evergreen.V25.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V23.Types.AuthenticationResult p0 ->
            Evergreen.V25.Types.AuthenticationResult p0

        Evergreen.V23.Types.GameStateUpdate p0 ->
            Evergreen.V25.Types.GameStateUpdate
                { currentUser = p0.currentUser
                , currentRound = p0.currentRound |> Maybe.map migrate_Types_FrontendRound
                , usersGuess = p0.usersGuess
                , pastRounds = p0.pastRounds |> List.map migrate_Types_UncensoredRound
                , avatarList = p0.avatarList
                }

        Evergreen.V23.Types.RoundCreated p0 ->
            Evergreen.V25.Types.RoundCreated (p0 |> migrate_Types_CensoredRound)

        Evergreen.V23.Types.GuessSubmitted p0 ->
            Evergreen.V25.Types.GuessSubmitted (p0 |> migrate_Types_Guess)

        Evergreen.V23.Types.RoundClosed p0 ->
            Evergreen.V25.Types.RoundClosed (p0 |> migrate_Types_UncensoredRound)

        Evergreen.V23.Types.ErrorMessage p0 ->
            Evergreen.V25.Types.ErrorMessage p0


migrate_Types_Round : (actualLocationType_old -> actualLocationType_new) -> (guessType_old -> guessType_new) -> promptType_new -> Evergreen.V23.Types.Round actualLocationType_old guessType_old -> Evergreen.V25.Types.Round promptType_new actualLocationType_new guessType_new
migrate_Types_Round migrate_actualLocationType migrate_guessType prompt old =
    { actualLocation = old.actualLocation |> migrate_actualLocationType
    , prompt = prompt
    , startTime = old.startTime
    , endTime = old.endTime
    , guesses = old.guesses |> Dict.map (always migrate_guessType)
    , isOpen = old.isOpen
    }


migrate_Types_UncensoredRound : Evergreen.V23.Types.UncensoredRound -> Evergreen.V25.Types.UncensoredRound
migrate_Types_UncensoredRound old =
    old |> migrate_Types_Round migrate_Types_Location migrate_Types_Guess ""


migrate_Types_CensoredRound : Evergreen.V23.Types.CensoredRound -> Evergreen.V25.Types.CensoredRound
migrate_Types_CensoredRound old =
    old |> migrate_Types_Round identity identity ()
