module Evergreen.Migrate.V27 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V25.Types
import Evergreen.V27.Types
import Lamdera.Migrations exposing (..)


frontendModel : Evergreen.V25.Types.FrontendModel -> ModelMigration Evergreen.V27.Types.FrontendModel Evergreen.V27.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V25.Types.BackendModel -> ModelMigration Evergreen.V27.Types.BackendModel Evergreen.V27.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V25.Types.FrontendMsg -> MsgMigration Evergreen.V27.Types.FrontendMsg Evergreen.V27.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V25.Types.ToBackend -> MsgMigration Evergreen.V27.Types.ToBackend Evergreen.V27.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V25.Types.BackendMsg -> MsgMigration Evergreen.V27.Types.BackendMsg Evergreen.V27.Types.BackendMsg
backendMsg old =
    MsgMigrated ( migrate_Types_BackendMsg old, Cmd.none )


toFrontend : Evergreen.V25.Types.ToFrontend -> MsgMigration Evergreen.V27.Types.ToFrontend Evergreen.V27.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_BackendMsg : Evergreen.V25.Types.BackendMsg -> Evergreen.V27.Types.BackendMsg
migrate_Types_BackendMsg old =
    case old of
        Evergreen.V25.Types.NoOpBackendMsg ->
            Evergreen.V27.Types.NoOpBackendMsg

        Evergreen.V25.Types.Tick p0 ->
            Evergreen.V27.Types.Tick p0

        Evergreen.V25.Types.GotImageGenerationResult p0 p1 ->
            Evergreen.V27.Types.GotImageGenerationResult p0 p1
