module Evergreen.Migrate.V31 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V27.Types
import Evergreen.V31.Types
import Lamdera.Migrations exposing (..)
import Random


frontendModel : Evergreen.V27.Types.FrontendModel -> ModelMigration Evergreen.V31.Types.FrontendModel Evergreen.V31.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V27.Types.BackendModel -> ModelMigration Evergreen.V31.Types.BackendModel Evergreen.V31.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V27.Types.FrontendMsg -> MsgMigration Evergreen.V31.Types.FrontendMsg Evergreen.V31.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V27.Types.ToBackend -> MsgMigration Evergreen.V31.Types.ToBackend Evergreen.V31.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V27.Types.BackendMsg -> MsgMigration Evergreen.V31.Types.BackendMsg Evergreen.V31.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V27.Types.ToFrontend -> MsgMigration Evergreen.V31.Types.ToFrontend Evergreen.V31.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_BackendModel : Evergreen.V27.Types.BackendModel -> Evergreen.V31.Types.BackendModel
migrate_Types_BackendModel old =
    { users = old.users
    , rounds = old.rounds
    , userSessions = old.userSessions
    , failedAuthentications = old.failedAuthentications
    , now = old.now
    , seed = Random.initialSeed 0
    }


migrate_Types_Location : Evergreen.V27.Types.Location -> Evergreen.V31.Types.Location
migrate_Types_Location old =
    old


migrate_Types_ToBackend : Evergreen.V27.Types.ToBackend -> Evergreen.V31.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V27.Types.AuthenticateWithTelegram p0 ->
            Evergreen.V31.Types.AuthenticateWithTelegram p0

        Evergreen.V27.Types.LogoutUser ->
            Evergreen.V31.Types.LogoutUser

        Evergreen.V27.Types.AuthenticateAsRay ->
            Evergreen.V31.Types.AuthenticateAsRay

        Evergreen.V27.Types.AuthenticateAsRegularUser ->
            Evergreen.V31.Types.AuthenticateAsRegularUser

        Evergreen.V27.Types.CreateNewRound p0 p1 ->
            Evergreen.V31.Types.CreateNewRound (p0 |> migrate_Types_Location) p1

        Evergreen.V27.Types.SubmitUserGuess p0 ->
            Evergreen.V31.Types.SubmitUserGuess (p0 |> migrate_Types_Location)
                ""

        Evergreen.V27.Types.EndCurrentRound ->
            Evergreen.V31.Types.EndCurrentRound

        Evergreen.V27.Types.RequestCurrentGameState ->
            Evergreen.V31.Types.RequestCurrentGameState

        Evergreen.V27.Types.RequestRoundHistory ->
            Evergreen.V31.Types.RequestRoundHistory
