module Evergreen.Migrate.V34 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V31.Types
import Evergreen.V34.Types
import Lamdera.Migrations exposing (..)


frontendModel : Evergreen.V31.Types.FrontendModel -> ModelMigration Evergreen.V34.Types.FrontendModel Evergreen.V34.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V31.Types.BackendModel -> ModelMigration Evergreen.V34.Types.BackendModel Evergreen.V34.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V31.Types.FrontendMsg -> MsgMigration Evergreen.V34.Types.FrontendMsg Evergreen.V34.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V31.Types.ToBackend -> MsgMigration Evergreen.V34.Types.ToBackend Evergreen.V34.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V31.Types.BackendMsg -> MsgMigration Evergreen.V34.Types.BackendMsg Evergreen.V34.Types.BackendMsg
backendMsg old =
    MsgMigrated ( migrate_Types_BackendMsg old, Cmd.none )


toFrontend : Evergreen.V31.Types.ToFrontend -> MsgMigration Evergreen.V34.Types.ToFrontend Evergreen.V34.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_BackendModel : Evergreen.V31.Types.BackendModel -> Evergreen.V34.Types.BackendModel
migrate_Types_BackendModel old =
    { users = old.users
    , rounds =
        old.rounds
            |> List.indexedMap
                (\idx round ->
                    if idx == 0 then
                        { round | guesses = round.guesses |> Dict.remove 8814284 }

                    else
                        round
                )
    , userSessions = old.userSessions
    , failedAuthentications = old.failedAuthentications
    , now = old.now
    , seed = old.seed
    , evergreenTrigger = []
    }


migrate_Types_BackendMsg : Evergreen.V31.Types.BackendMsg -> Evergreen.V34.Types.BackendMsg
migrate_Types_BackendMsg old =
    case old of
        Evergreen.V31.Types.NoOpBackendMsg ->
            Evergreen.V34.Types.NoOpBackendMsg

        Evergreen.V31.Types.Tick p0 ->
            Evergreen.V34.Types.Tick p0

        Evergreen.V31.Types.GotImageGenerationResult p0 p1 ->
            Evergreen.V34.Types.NoOpBackendMsg

        Evergreen.V31.Types.GotGeocodeResult p0 p1 p2 ->
            Evergreen.V34.Types.GotGeocodeResult p0 p1 p2
